# Generated by Django 4.2.7 on 2023-11-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("division", "0003_rename_divition_name_division_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="District_Name",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "divi_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="division.division_name",
                    ),
                ),
            ],
        ),
    ]
