# Generated by Django 4.2.7 on 2023-11-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("station", "0001_initial"),
        ("division", "0003_rename_divition_name_division_name_and_more"),
        ("hospital", "0001_initial"),
        ("district", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="address_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hos_name", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(upload_to="productimg")),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "district_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="district.district_name",
                    ),
                ),
                (
                    "division_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="division.division_name",
                    ),
                ),
                (
                    "hos_type_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospital_categories",
                    ),
                ),
                (
                    "station_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="station.station",
                    ),
                ),
            ],
        ),
    ]
