# Generated by Django 4.2.7 on 2023-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address_name",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
