# Generated by Django 4.2.7 on 2023-11-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("district", "0001_initial"),
        ("division", "0003_rename_divition_name_division_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dis_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="district.district_name",
                    ),
                ),
                (
                    "divi_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="division.division_name",
                    ),
                ),
            ],
        ),
    ]
