# Generated by Django 4.2.7 on 2023-11-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hospital_categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hos_cat",
                    models.CharField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
            ],
        ),
    ]
