# Generated by Django 4.2.7 on 2023-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0002_alter_user_register_v_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
