# Generated by Django 4.2.7 on 2023-11-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("address", "0002_alter_address_name_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital_map",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("longitude", models.CharField(max_length=50)),
                ("latitude", models.CharField(max_length=50)),
                (
                    "hospital_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.address_name",
                    ),
                ),
            ],
        ),
    ]
