# Generated by Django 4.2.7 on 2023-11-28 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_map", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital_map",
            old_name="hospital_id",
            new_name="hospital_fk",
        ),
    ]
