# Generated by Django 4.2.7 on 2023-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Divition_Name",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
            ],
        ),
    ]
