# Generated by Django 4.2.7 on 2023-11-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("division", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="divition_name",
            old_name="name",
            new_name="divition",
        ),
        migrations.AlterField(
            model_name="divition_name",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
