# Generated by Django 4.2.7 on 2023-11-26 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("division", "0002_rename_name_divition_name_divition_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Divition_Name",
            new_name="Division_Name",
        ),
        migrations.RenameField(
            model_name="division_name",
            old_name="divition",
            new_name="division",
        ),
    ]
